<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Bob.fs" />
        <Compile Include="BookingUpForBeauty.fs" />
        <Compile Include="BirdWatcher.fs" />
        <Compile Include="GuessingGame.fs" />
        <Compile Include="Interest.fs" />
        <Compile Include="Program.fs"/>
    </ItemGroup>

</Project>
